//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Foundation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Members {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Members() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Foundation.Resources.Members", typeof(Members).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new instance that imlements &lt;code&gt;IAsyncCollection&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string AsyncCollection_Create_TItem___ {
            get {
                return ResourceManager.GetString("AsyncCollection.Create<TItem>()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new instance that imlements &lt;code&gt;IAsyncValue&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string AsyncValue_Create_TValue___ {
            get {
                return ResourceManager.GetString("AsyncValue.Create<TValue>()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Browse_ChildContent {
            get {
                return ResourceManager.GetString("Browse.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current page.
        /// </summary>
        internal static string Browse_CurrentPage {
            get {
                return ResourceManager.GetString("Browse.CurrentPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoked when &lt;code&gt;CurrentPage&lt;/code&gt; changes.
        /// </summary>
        internal static string Browse_CurrentPageChanged {
            get {
                return ResourceManager.GetString("Browse.CurrentPageChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets &lt;code&gt;CurrentPage&lt;/code&gt; to &lt;code&gt;0&lt;/code&gt;.
        /// </summary>
        internal static string Browse_MoveToFirstPage__ {
            get {
                return ResourceManager.GetString("Browse.MoveToFirstPage()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increments &lt;code&gt;CurrentPage&lt;/code&gt; when possible.
        /// </summary>
        internal static string Browse_MoveToNextPage__ {
            get {
                return ResourceManager.GetString("Browse.MoveToNextPage()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrements &lt;code&gt;CurrentPage&lt;/code&gt; when possible.
        /// </summary>
        internal static string Browse_MoveToPreviousPage__ {
            get {
                return ResourceManager.GetString("Browse.MoveToPreviousPage()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page size.
        /// </summary>
        internal static string Browse_PageSize {
            get {
                return ResourceManager.GetString("Browse.PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt;, persists page in the navigation query.
        /// </summary>
        internal static string Browse_Persist {
            get {
                return ResourceManager.GetString("Browse.Persist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items that make up the entities as an &lt;code&gt;IAsyncValue&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string Chart_Items {
            get {
                return ResourceManager.GetString("Chart.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; new items will be adopted without a full reload.
        /// </summary>
        internal static string Chart_Live {
            get {
                return ResourceManager.GetString("Chart.Live", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum value (default is &lt;code&gt;auto&lt;/code&gt;).
        /// </summary>
        internal static string Chart_Maximum {
            get {
                return ResourceManager.GetString("Chart.Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerical value for each entity.
        /// </summary>
        internal static string Chart_Value {
            get {
                return ResourceManager.GetString("Chart.Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered inside nested &lt;code&gt;Table&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string ChoiceField_ChildContent {
            get {
                return ResourceManager.GetString("ChoiceField.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to be rendered inside nested &lt;code&gt;Table&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string ChoiceField_Columns {
            get {
                return ResourceManager.GetString("ChoiceField.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate that determines value when this field is collapsed (defaults to &lt;code&gt;ToString()&lt;/code&gt;).
        /// </summary>
        internal static string ChoiceField_DisplayItem {
            get {
                return ResourceManager.GetString("ChoiceField.DisplayItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty template for nested &lt;code&gt;Table&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string ChoiceField_Empty {
            get {
                return ResourceManager.GetString("ChoiceField.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items for nested &lt;code&gt;Table&amp;lt;&amp;gt;&lt;/code&gt; as an &lt;code&gt;IAsyncCollection&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string ChoiceField_Items {
            get {
                return ResourceManager.GetString("ChoiceField.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a class (conditionally).
        /// </summary>
        internal static string ClassList_Add__ {
            get {
                return ResourceManager.GetString("ClassList.Add()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds classes (conditionally).
        /// </summary>
        internal static string ClassList_AddRange__ {
            get {
                return ResourceManager.GetString("ClassList.AddRange()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds classes from unmatched attributes (conditionally).
        /// </summary>
        internal static string ClassList_AddUnmatched__ {
            get {
                return ResourceManager.GetString("ClassList.AddUnmatched()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes a class (conditionally).
        /// </summary>
        internal static string ClassList_Remove__ {
            get {
                return ResourceManager.GetString("ClassList.Remove()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes classes (conditionally).
        /// </summary>
        internal static string ClassList_RemoveRange__ {
            get {
                return ResourceManager.GetString("ClassList.RemoveRange()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes classes from unmatched attributes (conditionally).
        /// </summary>
        internal static string ClassList_RemoveUnmatched__ {
            get {
                return ResourceManager.GetString("ClassList.RemoveUnmatched()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; the cell&apos;s content is center-aligned.
        /// </summary>
        internal static string Column_AlignCenter {
            get {
                return ResourceManager.GetString("Column.AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; the cell&apos;s content is right-aligned.
        /// </summary>
        internal static string Column_AlignEnd {
            get {
                return ResourceManager.GetString("Column.AlignEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; the cell&apos;s content is left-aligned.
        /// </summary>
        internal static string Column_AlignStart {
            get {
                return ResourceManager.GetString("Column.AlignStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell content to be rendered.
        /// </summary>
        internal static string Column_Cell {
            get {
                return ResourceManager.GetString("Column.Cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell content to be rendered (equivalent of &lt;code&gt;Cell&lt;/code&gt;).
        /// </summary>
        internal static string Column_ChildContent {
            get {
                return ResourceManager.GetString("Column.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression that makes up the column&apos;s default &lt;code&gt;Cell&lt;/code&gt; value.
        /// </summary>
        internal static string Column_Expression {
            get {
                return ResourceManager.GetString("Column.Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; the column uses the available width.
        /// </summary>
        internal static string Column_Fill {
            get {
                return ResourceManager.GetString("Column.Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header content to be rendered.
        /// </summary>
        internal static string Column_Header {
            get {
                return ResourceManager.GetString("Column.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column&apos;s title, that when set is used as the default value for &lt;code&gt;Header&lt;/code&gt;.
        /// </summary>
        internal static string Column_Title {
            get {
                return ResourceManager.GetString("Column.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; renders as &lt;code&gt;date-only&lt;/code&gt;.
        /// </summary>
        internal static string DateTimeField_Date {
            get {
                return ResourceManager.GetString("DateTimeField.Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; renders as &lt;code&gt;time-only&lt;/code&gt;.
        /// </summary>
        internal static string DateTimeField_Time {
            get {
                return ResourceManager.GetString("DateTimeField.Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Defer_ChildContent {
            get {
                return ResourceManager.GetString("Defer.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines wether the field receives focus on page load.
        /// </summary>
        internal static string Field_AutoFocus {
            get {
                return ResourceManager.GetString("Field.AutoFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines the field&apos;s value.
        /// </summary>
        internal static string Field_Expression {
            get {
                return ResourceManager.GetString("Field.Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines wether the field is read-only.
        /// </summary>
        internal static string Field_ReadOnly {
            get {
                return ResourceManager.GetString("Field.ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field&apos;s title.
        /// </summary>
        internal static string Field_Title {
            get {
                return ResourceManager.GetString("Field.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;false&lt;/code&gt; the field won&apos;t be rendered.
        /// </summary>
        internal static string Field_Visible {
            get {
                return ResourceManager.GetString("Field.Visible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string ForEach_ChildContent {
            get {
                return ResourceManager.GetString("ForEach.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items to be enumerated.
        /// </summary>
        internal static string ForEach_Items {
            get {
                return ResourceManager.GetString("ForEach.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Form_ChildContent {
            get {
                return ResourceManager.GetString("Form.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component&apos;s subject as an &lt;code&gt;IAsyncValue&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string Form_Subject {
            get {
                return ResourceManager.GetString("Form.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents wether the collection has been fully retrieved.
        /// </summary>
        internal static string IAsyncCollection_Complete {
            get {
                return ResourceManager.GetString("IAsyncCollection.Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves the amount of items retrieved so far.
        /// </summary>
        internal static string IAsyncCollection_Count {
            get {
                return ResourceManager.GetString("IAsyncCollection.Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves view for the provided page when needed and returns it.
        /// </summary>
        internal static string IAsyncCollection_GetView__ {
            get {
                return ResourceManager.GetString("IAsyncCollection.GetView()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieves value when needed and returns it.
        /// </summary>
        internal static string IAsyncValue_GetValue__ {
            get {
                return ResourceManager.GetString("IAsyncValue.GetValue()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the cache so the next to &lt;code&gt;GetView()&lt;/code&gt; will retrieve data.
        /// </summary>
        internal static string IAsyncValue_Reset__ {
            get {
                return ResourceManager.GetString("IAsyncValue.Reset()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets the subscriber add a handler that is invoked whenever the value is reset.
        /// </summary>
        internal static string IAsyncValue_Subscribe__ {
            get {
                return ResourceManager.GetString("IAsyncValue.Subscribe()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects the provided item.
        /// </summary>
        internal static string ISelection_Activate__ {
            get {
                return ResourceManager.GetString("ISelection.Activate()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last-selected or active item.
        /// </summary>
        internal static string ISelection_Cursor {
            get {
                return ResourceManager.GetString("ISelection.Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deselects the provided item.
        /// </summary>
        internal static string ISelection_Deactivate__ {
            get {
                return ResourceManager.GetString("ISelection.Deactivate()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents wether the provided item is selected.
        /// </summary>
        internal static string ISelection_IsActive__ {
            get {
                return ResourceManager.GetString("ISelection.IsActive()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents wether the multiple selection is allowed.
        /// </summary>
        internal static string ISelection_Multiple {
            get {
                return ResourceManager.GetString("ISelection.Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lets the subscriber add a handler that is invoked whenever the selection changes.
        /// </summary>
        internal static string ISelection_Subscribe__ {
            get {
                return ResourceManager.GetString("ISelection.Subscribe()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects or deselects the provided item, depending on wether it was already selected.
        /// </summary>
        internal static string ISelection_Toggle__ {
            get {
                return ResourceManager.GetString("ISelection.Toggle()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered when loaded (equivalent of &lt;code&gt;Loaded&lt;/code&gt;).
        /// </summary>
        internal static string Load_ChildContent {
            get {
                return ResourceManager.GetString("Load.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered when loaded.
        /// </summary>
        internal static string Load_Loaded {
            get {
                return ResourceManager.GetString("Load.Loaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered when loading.
        /// </summary>
        internal static string Load_Loading {
            get {
                return ResourceManager.GetString("Load.Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Component&apos;s subject as an &lt;code&gt;IAsyncValue&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string Load_Subject {
            get {
                return ResourceManager.GetString("Load.Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered, used for &lt;code&gt;MenuItem&lt;/code&gt; instances.
        /// </summary>
        internal static string Menu_ChildContent {
            get {
                return ResourceManager.GetString("Menu.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hides the menu.
        /// </summary>
        internal static string Menu_Hide__ {
            get {
                return ResourceManager.GetString("Menu.Hide()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unique name of the menu, for use by &lt;code&gt;MenuController&lt;/code&gt;.
        /// </summary>
        internal static string Menu_Name {
            get {
                return ResourceManager.GetString("Menu.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called whenever a menu item is pressed that doesn&apos;t have an &lt;code&gt;OnPressed&lt;/code&gt; handler itself.
        /// </summary>
        internal static string Menu_OnItemPressed {
            get {
                return ResourceManager.GetString("Menu.OnItemPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the menu.
        /// </summary>
        internal static string Menu_Show__ {
            get {
                return ResourceManager.GetString("Menu.Show()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the menu.
        /// </summary>
        internal static string Menu_Title {
            get {
                return ResourceManager.GetString("Menu.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered, used for &lt;code&gt;MenuItem&lt;/code&gt; instances.
        /// </summary>
        internal static string MenuItem_ChildContent {
            get {
                return ResourceManager.GetString("MenuItem.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The menu item&apos;s (optional) context, which can be queried in the &lt;code&gt;OnPressed&lt;/code&gt; handler.
        /// </summary>
        internal static string MenuItem_Context {
            get {
                return ResourceManager.GetString("MenuItem.Context", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determines wether the menu item is disabled.
        /// </summary>
        internal static string MenuItem_Disabled {
            get {
                return ResourceManager.GetString("MenuItem.Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Called whenever the menu item is pressed.
        /// </summary>
        internal static string MenuItem_OnPressed {
            get {
                return ResourceManager.GetString("MenuItem.OnPressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title of the menu item.
        /// </summary>
        internal static string MenuItem_Title {
            get {
                return ResourceManager.GetString("MenuItem.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Overlay_ChildContent {
            get {
                return ResourceManager.GetString("Overlay.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Respond_ChildContent {
            get {
                return ResourceManager.GetString("Respond.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delegate that determines wether &lt;code&gt;ChildContent&lt;/code&gt; should be visible.
        /// </summary>
        internal static string Respond_Condition {
            get {
                return ResourceManager.GetString("Respond.Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Scroll_ChildContent {
            get {
                return ResourceManager.GetString("Scroll.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only scrolls horizontally when &lt;code&gt;true&lt;/code&gt;.
        /// </summary>
        internal static string Scroll_Horizontal {
            get {
                return ResourceManager.GetString("Scroll.Horizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only scrolls vertically when &lt;code&gt;true&lt;/code&gt;.
        /// </summary>
        internal static string Scroll_Vertical {
            get {
                return ResourceManager.GetString("Scroll.Vertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content to be rendered.
        /// </summary>
        internal static string Select_ChildContent {
            get {
                return ResourceManager.GetString("Select.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance of &lt;code&gt;ISelection&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string Select_Selection {
            get {
                return ResourceManager.GetString("Select.Selection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new instance of &lt;code&gt;ISelection&amp;lt;&amp;gt;&lt;/code&gt; that functions as a multi-selection.
        /// </summary>
        internal static string Selection_Multiple_TItem___ {
            get {
                return ResourceManager.GetString("Selection.Multiple<TItem>()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates a new instance of &lt;code&gt;ISelection&amp;lt;&amp;gt;&lt;/code&gt; that functions as a single-selection.
        /// </summary>
        internal static string Selection_Single_TItem___ {
            get {
                return ResourceManager.GetString("Selection.Single<TItem>()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds an attribute (conditionally).
        /// </summary>
        internal static string StyleList_Add__ {
            get {
                return ResourceManager.GetString("StyleList.Add()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds attributes (conditionally).
        /// </summary>
        internal static string StyleList_AddRange__ {
            get {
                return ResourceManager.GetString("StyleList.AddRange()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds attributes from unmatched attributes (conditionally).
        /// </summary>
        internal static string StyleList_AddUnmatched__ {
            get {
                return ResourceManager.GetString("StyleList.AddUnmatched()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes an attribute (conditionally).
        /// </summary>
        internal static string StyleList_Remove__ {
            get {
                return ResourceManager.GetString("StyleList.Remove()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes attributes (conditionally).
        /// </summary>
        internal static string StyleList_RemoveRange__ {
            get {
                return ResourceManager.GetString("StyleList.RemoveRange()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes attributes from unmatched attributes (conditionally).
        /// </summary>
        internal static string StyleList_RemoveUnmatched__ {
            get {
                return ResourceManager.GetString("StyleList.RemoveUnmatched()", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to be rendered (equivalent of &lt;code&gt;Columns&lt;/code&gt;).
        /// </summary>
        internal static string Table_ChildContent {
            get {
                return ResourceManager.GetString("Table.ChildContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns to be rendered.
        /// </summary>
        internal static string Table_Columns {
            get {
                return ResourceManager.GetString("Table.Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty template.
        /// </summary>
        internal static string Table_Empty {
            get {
                return ResourceManager.GetString("Table.Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items that make up the rows as an &lt;code&gt;IAsyncCollection&amp;lt;&amp;gt;&lt;/code&gt;.
        /// </summary>
        internal static string Table_Items {
            get {
                return ResourceManager.GetString("Table.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When &lt;code&gt;true&lt;/code&gt; renders as a &lt;code&gt;textarea&lt;/code&gt;, otherwise as a &lt;code&gt;input&lt;/code&gt;.
        /// </summary>
        internal static string TextField_MultiLine {
            get {
                return ResourceManager.GetString("TextField.MultiLine", resourceCulture);
            }
        }
    }
}
